### ISSUE TITLE
Correlating sensor measurements.

### ISSUE THREAD

**Issue by niklad** [VegardIversen/touch_detection_with_accelerometer-array#2]
The idea is that the cross-correlation will enhance the similar patterns and attenuate the differences in the measurements, i.e. the direct signal is rather similar but delayed, while the reflections will be different depending on sensor placement.

**Comment by VegardIversen** [comment]
exactly

**Comment by niklad** [comment]
but does it funk that way?

**Comment by niklad** [comment]
Ble ikke så mye klokere av å se på det as

**Comment by VegardIversen** [comment]
tror de kan antas å funke sånn. Det er jo såpass stor forskjell mellom korrelasjonsverdiene

**Comment by niklad** [comment]
I følge min egen logikk over der da så skal vi da sitte igjen med refleksjoner kun i retningen parallelt med linja mellom sensorene? Med peaks i tiden bølgene bruker mellom dem?
